version: '3.4'
services:
  beidou-server:
    container_name: beidou-server
    build:
      context: /home/wudaown/git/BeiDou-Server
      dockerfile: /home/wudaown/git/BeiDou-docker/Dockerfile-local
    environment:
      TZ: Asia/Shanghai
    ports:
      - "8686:8686"
      - "8484:8484"
      - "7575-7577:7575-7577"
    command: 
      - java
      - -Xms512m
      - -Xmx2048m
      - -jar
      - BeiDou.jar
      - --mybatis-flex.datasource.mysql.url=jdbc:mysql://beidou-db:3306/beidou?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      - --mybatis-flex.datasource.mysql.username=root
      - --mybatis-flex.datasource.mysql.password=root
      - --gms.service.wan-host=192.168.1.58
      - --gms.service.lan-host=192.168.1.58
      - --gms.service.localhost=192.168.1.58
    depends_on:
      beidou-db:
        condition: service_healthy
    networks:
      - beidou-network

  beidou-db:
    container_name: beidou-db
    image: mysql:8.4.0
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./docker-db-data-local:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - beidou-network

networks:
  beidou-network:
    driver: bridge
